#!/usr/bin/bash

SRC_FOLDER="./src"
BIN_FOLDER="./bin"

dev() {
  # Control will enter here if $BIN_FOLDER doesn't exist.
  if [ ! -d "$BIN_FOLDER" ]; then
    mkdir $BIN_FOLDER
  fi

  # Compile source code and run main
  gcc -Wall -o $BIN_FOLDER/main $SRC_FOLDER/*.c -lpthread && ./$BIN_FOLDER/main $1
}

prod() {
  # Control will enter here if $BIN_FOLDER doesn't exist.
  if [ ! -d "$BIN_FOLDER" ]; then
    mkdir $BIN_FOLDER
  fi

  # Compile source code and run main
  gcc -o $BIN_FOLDER/main $SRC_FOLDER/*.c -lpthread && ./$BIN_FOLDER/main $1
}

clear && prod $1
